--- 
- name: checking diff b/w > and |
  hosts: all
  vars:
    variable1: |
      this is will 
      as it is 
    variable2: >
      this will
      collapse 
  tasks:
  - name: for | operator
    debug:
      var: variable1
  - name: for > operator
    debug:
      var: variable2  

