---
- name: Configure Lamp server
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  pre_tasks:
  - name: Update apt chache if needed.
    apt: update_cache
    cache_valid_time: 3600
  handlers:
  - name: restart apache
    service: 
      name: apache2
      state: restarted
  tasks:
  - name: Get software for apt repository
    apt: 
      name: 
        - python-apt
        - python-pycurl
      state: present
            
