---
  - name: Ensure apache is Install
    yum:
      name: "{{ apache_package }}"
      state: present 
  - name: copy the file 
    copy: 
      src: test.cfg
      dest: /tmp
    notify: restart httpd    
  - name: Ensure apache is running and started at boot
    service:
      name: "{{ apache_service }}" 
      state: started 
      enabled: true    