---
- name: Install Webserver 
  hosts: all 
  become: yes 
  tasks:
  - name: Installed Httpd 
    yum:
      name: httpd 
      state: latest 

    notify:  
    - Start httpd
    - Restart httpd 
  handlers:
    - name: Start httpd 
      service: 
       name: httpd 
       state: started

    - name: Restart httpd 
      service: 
        name: httpd 
        state: restarted      
           
 