---
- name: Breaking multiline
  hosts: all
  gather_facts: no
  vars: 
    variable1: |- 
      Here you see exactily like
      you see in the console 
      of the image
    variable2: >- 
      Here it will group 
      the sting with white
      space at the  end. 
  tasks:
  - name: Print variable1
    debug:
      msg: "{{ variable1.split('\n') }}"
  - name: Print variable2 
    debug:
      var: variable2      